import { Heart, Users, ShieldCheck } from "lucide-react";

export const ROLES = {
  family: {
    label: "Family",
    color: "bg-pink-500",
    light: "bg-pink-50",
    text: "text-pink-700",
    border: "border-pink-200",
    icon: Heart,
    emoji: "👨‍👩‍👧",
  },
  friend: {
    label: "Friend",
    color: "bg-purple-500",
    light: "bg-purple-50",
    text: "text-purple-700",
    border: "border-purple-200",
    icon: Users,
    emoji: "👯‍♀️",
  },
  guardian: {
    label: "Guardian",
    color: "bg-blue-600",
    light: "bg-blue-50",
    text: "text-blue-700",
    border: "border-blue-200",
    icon: ShieldCheck,
    emoji: "🛡️",
  },
};

export const INITIAL_CONTACTS = [
  {
    id: 1,
    name: "Mom",
    phone: "+91 98765 43210",
    role: "family",
    verified: true,
    primary: true,
    online: true,
    canSeeLocation: true,
    notify: true,
    avatar: "M",
    color: "bg-pink-500",
    relation: "Mother",
    lastActive: "Active now",
  },
  {
    id: 2,
    name: "Priya (Sister)",
    phone: "+91 98765 11122",
    role: "family",
    verified: true,
    primary: false,
    online: true,
    canSeeLocation: true,
    notify: true,
    avatar: "P",
    color: "bg-purple-500",
    relation: "Sister",
    lastActive: "Active now",
  },
  {
    id: 3,
    name: "Dad",
    phone: "+91 98765 55566",
    role: "family",
    verified: true,
    primary: false,
    online: false,
    canSeeLocation: true,
    notify: true,
    avatar: "D",
    color: "bg-blue-500",
    relation: "Father",
    lastActive: "2 min ago",
  },
  {
    id: 4,
    name: "Anjali",
    phone: "+91 98765 33344",
    role: "friend",
    verified: true,
    primary: false,
    online: true,
    canSeeLocation: true,
    notify: true,
    avatar: "A",
    color: "bg-orange-500",
    relation: "Best Friend",
    lastActive: "Active now",
  },
  {
    id: 5,
    name: "Neha",
    phone: "+91 98765 22233",
    role: "friend",
    verified: false,
    primary: false,
    online: false,
    canSeeLocation: false,
    notify: true,
    avatar: "N",
    color: "bg-teal-500",
    relation: "College friend",
    lastActive: "1 hr ago",
  },
  {
    id: 6,
    name: "Sunita Aunty",
    phone: "+91 98765 99988",
    role: "guardian",
    verified: true,
    primary: false,
    online: true,
    canSeeLocation: true,
    notify: true,
    avatar: "S",
    color: "bg-indigo-500",
    relation: "Neighbor • Verified",
    lastActive: "Active now",
  },
];
